# -*- coding: utf-8 -*-
"""my calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOhGKdtsimysyotlNBFehkbSFBPBXmcl
"""

#get input from the user
num1=float( input ("Enter the first number: "))
num2=float(input("Enter the second number: "))
operation=input("Enter +,-,*,/,//,**: ")
#Do the mathematical operations and print the end result
if operation =="+":
  result=num1+num2
  print(num1+num2)
elif operation =="-":
  result=num1-num2
  print(num1-num2)
elif operation =="*":
  result=num1*num2
  print(num1*num2)
elif operation =="/":
  result=num1/num2
  print(num1/num2)
elif operation =="//":
  result=num1//num2
  print(num1//num2)
elif operation =="**":
  result=num1**num2
  print(num1**num2)
else:
  print("invalid operation")