# -*- coding: utf-8 -*-
"""wk 5 assigment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOynniS0X9rcxofFM52R8NmKMyJ2CTRq
"""

# -------------------------------
# Assignment 1: Smartphone Class
# -------------------------------

class Smartphone:
    def __init__(self, brand, model, price):
        # Attributes
        self.brand = brand
        self.model = model
        self.price = price

    # Method: show details
    def details(self):
        print(f" Brand: {self.brand}, Model: {self.model}, Price: ${self.price}")

    # Method: make a call
    def call(self, number):
        print(f"{self.brand} {self.model} is calling {number}...")


# -------------------------------
# Inheritance: GamingPhone
# -------------------------------

class GamingPhone(Smartphone):
    def __init__(self, brand, model, price, cooling_system):
        # Inherit attributes from Smartphone using super()
        super().__init__(brand, model, price)
        self.cooling_system = cooling_system

    # Override details method (Polymorphism)
    def details(self):
        print(f" Brand: {self.brand}, Model: {self.model}, Price: ${self.price}, Cooling: {self.cooling_system}")

    # Extra method
    def play_game(self, game):
        print(f"Playing {game} smoothly with {self.cooling_system} cooling system!")


# -------------------------------
# Test Smartphone & GamingPhone
# -------------------------------

phone1 = Smartphone("Samsung", "Galaxy S24", 999)
gaming1 = GamingPhone("Asus", "ROG Phone 8", 1499, "Liquid Cooling")

# Call methods
phone1.details()
phone1.call("0700040045")

gaming1.details()
gaming1.play_game("Call of Duty")


# -------------------------------
# Activity 2: Polymorphism Challenge
# -------------------------------

class Car:
    def move(self):
        print(" Driving on the road!")

class Plane:
    def move(self):
        print(" Flying in the sky!")

class Boat:
    def move(self):
        print(" Sailing on the water!")

class Bicycle:
    def move(self):
        print(" Pedaling on the street!")

# Create a list of vehicles
vehicles = [Car(), Plane(), Boat(), Bicycle()]

# Use polymorphism: each .move() behaves differently
print("\n--- Vehicles in Action ---")
for v in vehicles:
    v.move()